### ISSUE TITLE
utf-8 bom

### ISSUE THREAD

**Issue by RX-3200** [rectcircle/save-as-text#1]
can you please add utf-8 bom to saved texts ?

**Comment by rectcircle** [comment]
Because the utf8 bom is generally only used on the windows platform, I add utf8 bom under windows platform browser. Other platforms don't add utf8 bom
```js
	var pf = window.navigator.platform;
	if (pf == "Win32" || pf == "Windows") {
		content = '\uFEFF' + content;
	}
```
